spring.application.name=Fenestra
spring.application.version=1.0.0
spring.profiles.active=local

logging.file.name=logs/FenestraServer.log
logging.level.root=INFO
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10
logging.logback.rollingpolicy.file-name-pattern=logs/FenestraServer_%d{yyyy-MM-dd}.%i.log

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false